# Generated by Django 3.0 on 2021-05-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=20)),
                ('hour', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
                ('new_price', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
