# Generated by Django 3.0 on 2021-05-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child_Info',
            fields=[
                ('childID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class_Info',
            fields=[
                ('classID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('className', models.CharField(default='未命名', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Child.Class_Info')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Child.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Child_Course_Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.DecimalField(decimal_places=2, max_digits=5)),
                ('childID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Child.Child_Info')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Child.Course')),
            ],
        ),
    ]
