# Generated by Django 3.0 on 2021-06-05 18:14

import Child.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_info',
            name='image',
            field=models.ImageField(max_length=255, upload_to=Child.util.UploadFilesReName.rename),
        ),
    ]
