# Generated by Django 3.0 on 2021-06-05 19:03

import Child.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Child', '0002_auto_20210605_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_info',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=Child.util.UploadFilesReName.rename),
        ),
    ]
